// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: FS_DASHBOARD

#include "ui/ui.h"

lv_obj_t * uic_inverterlabel;
lv_obj_t * uic_deltasignlabel;
lv_obj_t * uic_voltageunit;
lv_obj_t * uic_amperunit;
lv_obj_t * uic_Whe;
lv_obj_t * uic_celsius;
lv_obj_t * uic_kmt;
lv_obj_t * uic_percent;
lv_obj_t * uic_kmh;
lv_obj_t * uic_consolabel;
lv_obj_t * uic_deltalabel;
lv_obj_t * uic_invertertemplabel;
lv_obj_t * uic_enginetemplabel;
lv_obj_t * uic_enginetemp;
lv_obj_t * uic_brakevisu;
lv_obj_t * uic_throttlevisu;
lv_obj_t * uic_invertertemp;
lv_obj_t * uic_batterylevellabel;
lv_obj_t * uic_batterylevel;
lv_obj_t * uic_tripmeter;
lv_obj_t * uic_amperagelabel;
lv_obj_t * uic_amperage;
lv_obj_t * uic_voltagelabel;
lv_obj_t * uic_voltage;
lv_obj_t * uic_batterytemplabel;
lv_obj_t * uic_batterytemp;
lv_obj_t * uic_batterymax;
lv_obj_t * uic_deltaarc;
lv_obj_t * uic_speedlabel;
lv_obj_t * ui_Main_Screen = NULL;
lv_obj_t * ui_speedlabel = NULL;
lv_obj_t * ui_deltaarc = NULL;
lv_obj_t * ui_batterymax = NULL;
lv_obj_t * ui_batterytemp = NULL;
lv_obj_t * ui_batterytemplabel = NULL;
lv_obj_t * ui_voltage = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_voltagelabel = NULL;
lv_obj_t * ui_amperage = NULL;
lv_obj_t * ui_amperagelabel = NULL;
lv_obj_t * ui_tripmeter = NULL;
lv_obj_t * ui_batterylevel = NULL;
lv_obj_t * ui_batterylevellabel = NULL;
lv_obj_t * ui_invertertemp = NULL;
lv_obj_t * ui_throttlevisu = NULL;
lv_obj_t * ui_brakevisu = NULL;
lv_obj_t * ui_enginetemp = NULL;
lv_obj_t * ui_enginetemplabel = NULL;
lv_obj_t * ui_invertertemplabel = NULL;
lv_obj_t * ui_deltalabel = NULL;
lv_obj_t * ui_consolabel = NULL;
lv_obj_t * ui_kmh = NULL;
lv_obj_t * ui_percent = NULL;
lv_obj_t * ui_kmt = NULL;
lv_obj_t * ui_celsius = NULL;
lv_obj_t * ui_celsius1 = NULL;
lv_obj_t * ui_celsius2 = NULL;
lv_obj_t * ui_Whe = NULL;
lv_obj_t * ui_amperunit = NULL;
lv_obj_t * ui_voltageunit = NULL;
lv_obj_t * ui_deltasignlabel = NULL;
lv_obj_t * ui_enginelabel = NULL;
lv_obj_t * ui_inverterlabel = NULL;
lv_obj_t * ui_amperage1 = NULL;
// event funtions

// build funtions

void ui_Main_Screen_screen_init(void)
{
    ui_Main_Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Main_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Main_Screen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Main_Screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_speedlabel = lv_label_create(ui_Main_Screen);
    lv_obj_set_width(ui_speedlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_speedlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_speedlabel, -138);
    lv_obj_set_y(ui_speedlabel, -182);
    lv_obj_set_align(ui_speedlabel, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_speedlabel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_speedlabel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_long_mode(ui_speedlabel, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_speedlabel, "192");
    lv_obj_set_style_text_letter_space(ui_speedlabel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_speedlabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_speedlabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_speedlabel, &ui_font_speedfont, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_speedlabel, 256, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_deltaarc = lv_arc_create(ui_Main_Screen);
    lv_obj_set_width(ui_deltaarc, 350);
    lv_obj_set_height(ui_deltaarc, 350);
    lv_obj_set_align(ui_deltaarc, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_deltaarc, 0, 400);
    lv_arc_set_value(ui_deltaarc, 23);
    lv_arc_set_bg_angles(ui_deltaarc, 135, 45);
    lv_arc_set_mode(ui_deltaarc, LV_ARC_MODE_SYMMETRICAL);

    lv_obj_set_style_arc_color(ui_deltaarc, lv_color_hex(0x00AE00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_deltaarc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_deltaarc, lv_color_hex(0x00AE00), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_deltaarc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_batterymax = lv_arc_create(ui_Main_Screen);
    lv_obj_set_width(ui_batterymax, 420);
    lv_obj_set_height(ui_batterymax, 420);
    lv_obj_set_x(ui_batterymax, -2);
    lv_obj_set_y(ui_batterymax, 3);
    lv_obj_set_align(ui_batterymax, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_batterymax, 100);
    lv_arc_set_bg_angles(ui_batterymax, 242, 250);
    lv_arc_set_rotation(ui_batterymax, 1);
    lv_obj_set_style_arc_width(ui_batterymax, 17, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_batterymax, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_batterymax, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_batterymax, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_batterymax, 17, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_batterymax, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_batterymax, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_batterymax, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_batterymax, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_batterymax, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_batterytemp = lv_arc_create(ui_Main_Screen);
    lv_obj_set_width(ui_batterytemp, 420);
    lv_obj_set_height(ui_batterytemp, 420);
    lv_obj_set_x(ui_batterytemp, 2);
    lv_obj_set_y(ui_batterytemp, 1);
    lv_obj_set_align(ui_batterytemp, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_batterytemp, 0, 80);
    lv_arc_set_value(ui_batterytemp, 70);
    lv_arc_set_bg_angles(ui_batterytemp, 190, 250);
    lv_obj_set_style_arc_color(ui_batterytemp, lv_color_hex(0x636363), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_batterytemp, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_batterytemp, 17, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_batterytemp, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_batterytemp, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_batterytemp, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_batterytemp, 17, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_batterytemp, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_batterytemp, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_batterytemp, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_batterytemp, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_batterytemp, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_batterytemplabel = lv_label_create(ui_Main_Screen);
    lv_obj_set_width(ui_batterytemplabel, 85);
    lv_obj_set_height(ui_batterytemplabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_batterytemplabel, -159);
    lv_obj_set_y(ui_batterytemplabel, -204);
    lv_obj_set_align(ui_batterytemplabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_batterytemplabel, "65");
    lv_obj_set_style_text_align(ui_batterytemplabel, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_batterytemplabel, &ui_font_temperaturefont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_voltage = lv_bar_create(ui_Main_Screen);
    lv_bar_set_range(ui_voltage, 0, 350);
    lv_bar_set_value(ui_voltage, 280, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_voltage, 0, LV_ANIM_OFF);
    lv_obj_set_height(ui_voltage, 30);
    lv_obj_set_width(ui_voltage, lv_pct(40));
    lv_obj_set_x(ui_voltage, -204);
    lv_obj_set_y(ui_voltage, 183);
    lv_obj_set_align(ui_voltage, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_voltage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_voltage, lv_color_hex(0x1E1E1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_voltage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_voltage, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_voltage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_voltage, -900, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_voltage, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_voltage, lv_color_hex(0xF4F4F4), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_voltage, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Image4 = lv_img_create(ui_Main_Screen);
    lv_img_set_src(ui_Image4, &ui_img_batterytemp_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image4, -203);
    lv_obj_set_y(ui_Image4, -9);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image4, 40);

    ui_voltagelabel = lv_label_create(ui_Main_Screen);
    lv_obj_set_width(ui_voltagelabel, 58);
    lv_obj_set_height(ui_voltagelabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_voltagelabel, -354);
    lv_obj_set_y(ui_voltagelabel, -196);
    lv_obj_set_align(ui_voltagelabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_voltagelabel, "100");
    lv_obj_set_style_text_align(ui_voltagelabel, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_voltagelabel, &ui_font_voltagefont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_amperage = lv_bar_create(ui_Main_Screen);
    lv_bar_set_range(ui_amperage, 0, 300);
    lv_bar_set_value(ui_amperage, 200, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_amperage, 0, LV_ANIM_OFF);
    lv_obj_set_height(ui_amperage, 30);
    lv_obj_set_width(ui_amperage, lv_pct(20));
    lv_obj_set_x(ui_amperage, -208);
    lv_obj_set_y(ui_amperage, 23);
    lv_obj_set_align(ui_amperage, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_amperage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_amperage, lv_color_hex(0x1E1E1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_amperage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_amperage, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_amperage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_amperage, -900, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_amperage, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_amperage, lv_color_hex(0xAAEAFE), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_amperage, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_amperagelabel = lv_label_create(ui_Main_Screen);
    lv_obj_set_width(ui_amperagelabel, 77);
    lv_obj_set_height(ui_amperagelabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_amperagelabel, -630);
    lv_obj_set_y(ui_amperagelabel, -196);
    lv_obj_set_align(ui_amperagelabel, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_amperagelabel, "-300");
    lv_obj_set_style_text_align(ui_amperagelabel, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_amperagelabel, &ui_font_voltagefont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tripmeter = lv_label_create(ui_Main_Screen);
    lv_obj_set_width(ui_tripmeter, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tripmeter, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tripmeter, 0);
    lv_obj_set_y(ui_tripmeter, -114);
    lv_obj_set_align(ui_tripmeter, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tripmeter, "9.9");
    lv_obj_set_style_text_letter_space(ui_tripmeter, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_tripmeter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_tripmeter, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tripmeter, &ui_font_kmfont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_batterylevel = lv_bar_create(ui_Main_Screen);
    lv_bar_set_value(ui_batterylevel, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_batterylevel, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_batterylevel, 262);
    lv_obj_set_height(ui_batterylevel, 25);
    lv_obj_set_x(ui_batterylevel, 3);
    lv_obj_set_y(ui_batterylevel, 152);
    lv_obj_set_align(ui_batterylevel, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_batterylevel, lv_color_hex(0x105A09), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_batterylevel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_batterylevel, lv_color_hex(0x16F002), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_batterylevel, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_batterylevellabel = lv_label_create(ui_Main_Screen);
    lv_obj_set_width(ui_batterylevellabel, 55);
    lv_obj_set_height(ui_batterylevellabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_batterylevellabel, 0);
    lv_obj_set_y(ui_batterylevellabel, 186);
    lv_obj_set_align(ui_batterylevellabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_batterylevellabel, "100");
    lv_obj_set_style_text_align(ui_batterylevellabel, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_batterylevellabel, &ui_font_voltagefont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_invertertemp = lv_obj_create(ui_Main_Screen);
    lv_obj_set_width(ui_invertertemp, 123);
    lv_obj_set_height(ui_invertertemp, 94);
    lv_obj_set_x(ui_invertertemp, 323);
    lv_obj_set_y(ui_invertertemp, 155);
    lv_obj_set_align(ui_invertertemp, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_invertertemp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_invertertemp, lv_color_hex(0x07AD04), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_invertertemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_invertertemp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_invertertemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_throttlevisu = lv_bar_create(ui_Main_Screen);
    lv_bar_set_value(ui_throttlevisu, 85, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_throttlevisu, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_throttlevisu, 30);
    lv_obj_set_height(ui_throttlevisu, 170);
    lv_obj_set_x(ui_throttlevisu, 300);
    lv_obj_set_y(ui_throttlevisu, -133);
    lv_obj_set_align(ui_throttlevisu, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_throttlevisu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_throttlevisu, lv_color_hex(0x1E1E1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_throttlevisu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_throttlevisu, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_throttlevisu, lv_color_hex(0x23C300), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_throttlevisu, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_brakevisu = lv_bar_create(ui_Main_Screen);
    lv_bar_set_value(ui_brakevisu, 20, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_brakevisu, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_brakevisu, 30);
    lv_obj_set_height(ui_brakevisu, 170);
    lv_obj_set_x(ui_brakevisu, 356);
    lv_obj_set_y(ui_brakevisu, -133);
    lv_obj_set_align(ui_brakevisu, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_brakevisu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_brakevisu, lv_color_hex(0x1E1E1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_brakevisu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_brakevisu, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_brakevisu, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_brakevisu, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_enginetemp = lv_obj_create(ui_Main_Screen);
    lv_obj_set_width(ui_enginetemp, 123);
    lv_obj_set_height(ui_enginetemp, 94);
    lv_obj_set_x(ui_enginetemp, 321);
    lv_obj_set_y(ui_enginetemp, 44);
    lv_obj_set_align(ui_enginetemp, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_enginetemp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_enginetemp, lv_color_hex(0x07AD04), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_enginetemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_enginetemp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_enginetemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_enginetemplabel = lv_label_create(ui_Main_Screen);
    lv_obj_set_width(ui_enginetemplabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_enginetemplabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_enginetemplabel, -49);
    lv_obj_set_y(ui_enginetemplabel, 44);
    lv_obj_set_align(ui_enginetemplabel, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_enginetemplabel, "88");
    lv_obj_set_style_text_color(ui_enginetemplabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_enginetemplabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_enginetemplabel, &ui_font_temperaturefont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_invertertemplabel = lv_label_create(ui_Main_Screen);
    lv_obj_set_width(ui_invertertemplabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_invertertemplabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_invertertemplabel, -49);
    lv_obj_set_y(ui_invertertemplabel, 155);
    lv_obj_set_align(ui_invertertemplabel, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_invertertemplabel, "99");
    lv_obj_set_style_text_color(ui_invertertemplabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_invertertemplabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_invertertemplabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_invertertemplabel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_invertertemplabel, &ui_font_temperaturefont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_deltalabel = lv_label_create(ui_Main_Screen);
    lv_obj_set_width(ui_deltalabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_deltalabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_deltalabel, 0);
    lv_obj_set_y(ui_deltalabel, 26);
    lv_obj_set_align(ui_deltalabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_deltalabel, "3.34");
    lv_obj_set_style_text_color(ui_deltalabel, lv_color_hex(0x00AE00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_deltalabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_deltalabel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_deltalabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_deltalabel, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_deltalabel, &ui_font_deltafont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_consolabel = lv_label_create(ui_Main_Screen);
    lv_obj_set_width(ui_consolabel, 80);
    lv_obj_set_height(ui_consolabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_consolabel, -31);
    lv_obj_set_y(ui_consolabel, 119);
    lv_obj_set_align(ui_consolabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_consolabel, "124.2");
    lv_obj_set_style_text_color(ui_consolabel, lv_color_hex(0x9C9C9C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_consolabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_consolabel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_consolabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_consolabel, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_consolabel, &ui_font_kmfont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_kmh = lv_label_create(ui_Main_Screen);
    lv_obj_set_width(ui_kmh, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_kmh, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_kmh, 238);
    lv_obj_set_y(ui_kmh, -140);
    lv_obj_set_align(ui_kmh, LV_ALIGN_CENTER);
    lv_label_set_text(ui_kmh, "km/h");
    lv_obj_set_style_text_font(ui_kmh, &ui_font_unitfont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_percent = lv_label_create(ui_Main_Screen);
    lv_obj_set_width(ui_percent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_percent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_percent, 37);
    lv_obj_set_y(ui_percent, 192);
    lv_obj_set_align(ui_percent, LV_ALIGN_CENTER);
    lv_label_set_text(ui_percent, "%");
    lv_obj_set_style_text_font(ui_percent, &ui_font_unitfont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_kmt = lv_label_create(ui_Main_Screen);
    lv_obj_set_width(ui_kmt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_kmt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_kmt, 47);
    lv_obj_set_y(ui_kmt, -111);
    lv_obj_set_align(ui_kmt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_kmt, "km");
    lv_obj_set_style_text_font(ui_kmt, &ui_font_unitfont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_celsius = lv_label_create(ui_Main_Screen);
    lv_obj_set_width(ui_celsius, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_celsius, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_celsius, 365);
    lv_obj_set_y(ui_celsius, 136);
    lv_obj_set_align(ui_celsius, LV_ALIGN_CENTER);
    lv_label_set_text(ui_celsius, "°C");
    lv_obj_set_style_text_color(ui_celsius, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_celsius, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_celsius, &ui_font_unitfont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_celsius1 = lv_label_create(ui_Main_Screen);
    lv_obj_set_width(ui_celsius1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_celsius1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_celsius1, 365);
    lv_obj_set_y(ui_celsius1, 24);
    lv_obj_set_align(ui_celsius1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_celsius1, "°C");
    lv_obj_set_style_text_color(ui_celsius1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_celsius1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_celsius1, &ui_font_unitfont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_celsius2 = lv_label_create(ui_Main_Screen);
    lv_obj_set_width(ui_celsius2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_celsius2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_celsius2, -103);
    lv_obj_set_y(ui_celsius2, -213);
    lv_obj_set_align(ui_celsius2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_celsius2, "°C");
    lv_obj_set_style_text_color(ui_celsius2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_celsius2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_celsius2, &ui_font_unitfont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Whe = lv_label_create(ui_Main_Screen);
    lv_obj_set_width(ui_Whe, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Whe, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Whe, 47);
    lv_obj_set_y(ui_Whe, 122);
    lv_obj_set_align(ui_Whe, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Whe, "Wh/km");
    lv_obj_set_style_text_color(ui_Whe, lv_color_hex(0x9C9C9C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Whe, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Whe, &ui_font_unitfont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_amperunit = lv_label_create(ui_Main_Screen);
    lv_obj_set_width(ui_amperunit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_amperunit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_amperunit, -273);
    lv_obj_set_y(ui_amperunit, 204);
    lv_obj_set_align(ui_amperunit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_amperunit, "A");
    lv_obj_set_style_text_color(ui_amperunit, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_amperunit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_amperunit, &ui_font_voltagefont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_voltageunit = lv_label_create(ui_Main_Screen);
    lv_obj_set_width(ui_voltageunit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_voltageunit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_voltageunit, -350);
    lv_obj_set_y(ui_voltageunit, 204);
    lv_obj_set_align(ui_voltageunit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_voltageunit, "V");
    lv_obj_set_style_text_color(ui_voltageunit, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_voltageunit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_voltageunit, &ui_font_voltagefont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_deltasignlabel = lv_label_create(ui_Main_Screen);
    lv_obj_set_width(ui_deltasignlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_deltasignlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_deltasignlabel, 0);
    lv_obj_set_y(ui_deltasignlabel, -57);
    lv_obj_set_align(ui_deltasignlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_deltasignlabel, "+");
    lv_obj_set_style_text_color(ui_deltasignlabel, lv_color_hex(0x20C200), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_deltasignlabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_deltasignlabel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_deltasignlabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_deltasignlabel, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_deltasignlabel, &ui_font_temperaturefont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_enginelabel = lv_label_create(ui_Main_Screen);
    lv_obj_set_width(ui_enginelabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_enginelabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_enginelabel, 288);
    lv_obj_set_y(ui_enginelabel, -14);
    lv_obj_set_align(ui_enginelabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_enginelabel, "ENGINE");
    lv_obj_set_style_text_color(ui_enginelabel, lv_color_hex(0x606060), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_enginelabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_enginelabel, &ui_font_letterfont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_inverterlabel = lv_label_create(ui_Main_Screen);
    lv_obj_set_width(ui_inverterlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_inverterlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_inverterlabel, 297);
    lv_obj_set_y(ui_inverterlabel, 213);
    lv_obj_set_align(ui_inverterlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_inverterlabel, "INVERTER");
    lv_obj_set_style_text_color(ui_inverterlabel, lv_color_hex(0x606060), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_inverterlabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_inverterlabel, &ui_font_letterfont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_amperage1 = lv_bar_create(ui_Main_Screen);
    lv_bar_set_range(ui_amperage1, 0, 300);
    lv_bar_set_value(ui_amperage1, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_amperage1, 0, LV_ANIM_OFF);
    lv_obj_set_height(ui_amperage1, 30);
    lv_obj_set_width(ui_amperage1, lv_pct(20));
    lv_obj_set_x(ui_amperage1, -208);
    lv_obj_set_y(ui_amperage1, 183);
    lv_obj_set_align(ui_amperage1, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_amperage1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_amperage1, lv_color_hex(0xA8FCA9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_amperage1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_amperage1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_amperage1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_amperage1, -900, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_amperage1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_amperage1, lv_color_hex(0x1E1E1E), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_amperage1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    uic_speedlabel = ui_speedlabel;
    uic_deltaarc = ui_deltaarc;
    uic_batterymax = ui_batterymax;
    uic_batterytemp = ui_batterytemp;
    uic_batterytemplabel = ui_batterytemplabel;
    uic_voltage = ui_voltage;
    uic_voltagelabel = ui_voltagelabel;
    uic_amperage = ui_amperage;
    uic_amperagelabel = ui_amperagelabel;
    uic_tripmeter = ui_tripmeter;
    uic_batterylevel = ui_batterylevel;
    uic_batterylevellabel = ui_batterylevellabel;
    uic_invertertemp = ui_invertertemp;
    uic_throttlevisu = ui_throttlevisu;
    uic_brakevisu = ui_brakevisu;
    uic_enginetemp = ui_enginetemp;
    uic_enginetemplabel = ui_enginetemplabel;
    uic_invertertemplabel = ui_invertertemplabel;
    uic_deltalabel = ui_deltalabel;
    uic_consolabel = ui_consolabel;
    uic_kmh = ui_kmh;
    uic_percent = ui_percent;
    uic_kmt = ui_kmt;
    uic_celsius = ui_celsius;
    uic_Whe = ui_Whe;
    uic_amperunit = ui_amperunit;
    uic_voltageunit = ui_voltageunit;
    uic_deltasignlabel = ui_deltasignlabel;
    uic_inverterlabel = ui_inverterlabel;

}

void ui_Main_Screen_screen_destroy(void)
{
    if(ui_Main_Screen) lv_obj_del(ui_Main_Screen);

    // NULL screen variables
    ui_Main_Screen = NULL;
    uic_speedlabel = NULL;
    ui_speedlabel = NULL;
    uic_deltaarc = NULL;
    ui_deltaarc = NULL;
    uic_batterymax = NULL;
    ui_batterymax = NULL;
    uic_batterytemp = NULL;
    ui_batterytemp = NULL;
    uic_batterytemplabel = NULL;
    ui_batterytemplabel = NULL;
    uic_voltage = NULL;
    ui_voltage = NULL;
    ui_Image4 = NULL;
    uic_voltagelabel = NULL;
    ui_voltagelabel = NULL;
    uic_amperage = NULL;
    ui_amperage = NULL;
    uic_amperagelabel = NULL;
    ui_amperagelabel = NULL;
    uic_tripmeter = NULL;
    ui_tripmeter = NULL;
    uic_batterylevel = NULL;
    ui_batterylevel = NULL;
    uic_batterylevellabel = NULL;
    ui_batterylevellabel = NULL;
    uic_invertertemp = NULL;
    ui_invertertemp = NULL;
    uic_throttlevisu = NULL;
    ui_throttlevisu = NULL;
    uic_brakevisu = NULL;
    ui_brakevisu = NULL;
    uic_enginetemp = NULL;
    ui_enginetemp = NULL;
    uic_enginetemplabel = NULL;
    ui_enginetemplabel = NULL;
    uic_invertertemplabel = NULL;
    ui_invertertemplabel = NULL;
    uic_deltalabel = NULL;
    ui_deltalabel = NULL;
    uic_consolabel = NULL;
    ui_consolabel = NULL;
    uic_kmh = NULL;
    ui_kmh = NULL;
    uic_percent = NULL;
    ui_percent = NULL;
    uic_kmt = NULL;
    ui_kmt = NULL;
    uic_celsius = NULL;
    ui_celsius = NULL;
    ui_celsius1 = NULL;
    ui_celsius2 = NULL;
    uic_Whe = NULL;
    ui_Whe = NULL;
    uic_amperunit = NULL;
    ui_amperunit = NULL;
    uic_voltageunit = NULL;
    ui_voltageunit = NULL;
    uic_deltasignlabel = NULL;
    ui_deltasignlabel = NULL;
    ui_enginelabel = NULL;
    uic_inverterlabel = NULL;
    ui_inverterlabel = NULL;
    ui_amperage1 = NULL;

}

void ui_Main_Screen_screen_relocalize(void)
{
    // label widgets on screen

}
