// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: FS_DASHBOARD

#ifndef UI_MAIN_SCREEN_H
#define UI_MAIN_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Main_Screen
extern void ui_Main_Screen_screen_init(void);
extern void ui_Main_Screen_screen_destroy(void);
extern void ui_Main_Screen_screen_relocalize(void);
extern lv_obj_t * ui_Main_Screen;
extern lv_obj_t * ui_speedlabel;
extern lv_obj_t * ui_deltaarc;
extern lv_obj_t * ui_batterymax;
extern lv_obj_t * ui_batterytemp;
extern lv_obj_t * ui_batterytemplabel;
extern lv_obj_t * ui_voltage;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_voltagelabel;
extern lv_obj_t * ui_amperage;
extern lv_obj_t * ui_amperagelabel;
extern lv_obj_t * ui_tripmeter;
extern lv_obj_t * ui_batterylevel;
extern lv_obj_t * ui_batterylevellabel;
extern lv_obj_t * ui_invertertemp;
extern lv_obj_t * ui_throttlevisu;
extern lv_obj_t * ui_brakevisu;
extern lv_obj_t * ui_enginetemp;
extern lv_obj_t * ui_enginetemplabel;
extern lv_obj_t * ui_invertertemplabel;
extern lv_obj_t * ui_deltalabel;
extern lv_obj_t * ui_consolabel;
extern lv_obj_t * ui_kmh;
extern lv_obj_t * ui_percent;
extern lv_obj_t * ui_kmt;
extern lv_obj_t * ui_celsius;
extern lv_obj_t * ui_celsius1;
extern lv_obj_t * ui_celsius2;
extern lv_obj_t * ui_Whe;
extern lv_obj_t * ui_amperunit;
extern lv_obj_t * ui_voltageunit;
extern lv_obj_t * ui_deltasignlabel;
extern lv_obj_t * ui_enginelabel;
extern lv_obj_t * ui_inverterlabel;
extern lv_obj_t * ui_amperage1;
// CUSTOM VARIABLES
extern lv_obj_t * uic_speedlabel;
extern lv_obj_t * uic_deltaarc;
extern lv_obj_t * uic_batterymax;
extern lv_obj_t * uic_batterytemp;
extern lv_obj_t * uic_batterytemplabel;
extern lv_obj_t * uic_voltage;
extern lv_obj_t * uic_voltagelabel;
extern lv_obj_t * uic_amperage;
extern lv_obj_t * uic_amperagelabel;
extern lv_obj_t * uic_tripmeter;
extern lv_obj_t * uic_batterylevel;
extern lv_obj_t * uic_batterylevellabel;
extern lv_obj_t * uic_invertertemp;
extern lv_obj_t * uic_throttlevisu;
extern lv_obj_t * uic_brakevisu;
extern lv_obj_t * uic_enginetemp;
extern lv_obj_t * uic_enginetemplabel;
extern lv_obj_t * uic_invertertemplabel;
extern lv_obj_t * uic_deltalabel;
extern lv_obj_t * uic_consolabel;
extern lv_obj_t * uic_kmh;
extern lv_obj_t * uic_percent;
extern lv_obj_t * uic_kmt;
extern lv_obj_t * uic_celsius;
extern lv_obj_t * uic_Whe;
extern lv_obj_t * uic_amperunit;
extern lv_obj_t * uic_voltageunit;
extern lv_obj_t * uic_deltasignlabel;
extern lv_obj_t * uic_inverterlabel;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

