// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: FS_DASHBOARD

#ifndef _FS_DASHBOARD_UI_H
#define _FS_DASHBOARD_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Main_Screen.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_batterytemp_png);    // assets/batterytemp.png

// FONTS
LV_FONT_DECLARE(ui_font_deltafont);
LV_FONT_DECLARE(ui_font_kmfont);
LV_FONT_DECLARE(ui_font_letterfont);
LV_FONT_DECLARE(ui_font_speedfont);
LV_FONT_DECLARE(ui_font_temperaturefont);
LV_FONT_DECLARE(ui_font_unitfont);
LV_FONT_DECLARE(ui_font_voltagefont);

// UI INIT
void ui_init(void);
void ui_destroy(void);
void ui_relocalize(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
